### ISSUE TITLE
Permission denied when trying to send broadcast message on Android 7

### ISSUE THREAD

**Issue by showlabor** [Sciss/NetUtil#4]
Hi,
when I try to send a message to a UDP broadcast address I get a "java.net.SocketException: Permission denied" exception. This is not a permission issue on Android as I can get broadcast messages through from the same app with the same permissions with JavaOSC and liblo. The very same app unaltered runs fine with NetUtil on Android 6 and below.
If there's still some active development on NetUtil I can provide a stripped down sample app. Just let me know!

**Comment by Sciss** [comment]
Hi, thanks for the report. Indeed I'm not actively developing this, as I have moved to Scala, but I am happy to incorporate any bug fixes. Unfortunately, I don't have any Android devices to test; but if you can narrow down the problem and perhaps even create a pull request, I am happy to review and eventually merge it.

**Comment by showlabor** [comment]
Great to see that you're at least still monitoring issue reports!
All I can say at the moment is that it's the ```final DatagramChannel newCh = DatagramChannel.open();``` line (OSCTransmitter.java:654, called from OSCServer.start() ) that fails and leads to the permission denied exception.
BTW, you don't need an Android device to test. The code breaks happily even on the emulator ;-)
If I find more I'll let you know.

**Comment by showlabor** [comment]
Thanks for accepting the pull request!
